services:
  redis:
    image: redis
    container_name: redis_rl
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_CACHE_KEY}
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_CACHE_KEY}
    env_file:
      - .env

volumes:
  redis-data:
